"""Chat import 公共导出。"""

from .models import (
    AttachmentMaterializationResult,
    DetectedConversation,
    DetectedParticipant,
    ImportAttachmentEnvelope,
    ImportBatch,
    ImportConversationMapping,
    ImportCursor,
    ImportDedupeEntry,
    ImportedChatMessage,
    ImportFactDisposition,
    ImportFactHint,
    ImportInputRef,
    ImportMappingProfile,
    ImportReport,
    ImportSenderMapping,
    ImportSourceFormat,
    ImportSourceType,
    ImportStatus,
    ImportSummary,
    ImportWindow,
    ImportWindowKind,
)
from .service import ChatImportProcessor, ImportWindowDraft, PreparedImport, derive_import_source_id
from .sqlite_init import init_chat_import_db, verify_chat_import_tables
from .store import SqliteChatImportStore

__all__ = [
    "ChatImportProcessor",
    "PreparedImport",
    "ImportWindowDraft",
    "ImportedChatMessage",
    "ImportFactHint",
    "ImportInputRef",
    "ImportSourceType",
    "DetectedConversation",
    "DetectedParticipant",
    "ImportConversationMapping",
    "ImportSenderMapping",
    "ImportMappingProfile",
    "ImportAttachmentEnvelope",
    "AttachmentMaterializationResult",
    "ImportBatch",
    "ImportCursor",
    "ImportDedupeEntry",
    "ImportWindow",
    "ImportSummary",
    "ImportReport",
    "ImportStatus",
    "ImportSourceFormat",
    "ImportWindowKind",
    "ImportFactDisposition",
    "SqliteChatImportStore",
    "derive_import_source_id",
    "init_chat_import_db",
    "verify_chat_import_tables",
]
