"""OctoAgent Core Domain Models -- 公共类型导出

所有公共模型类型从此入口导入。
"""

from .artifact import Artifact, ArtifactPart
from .backup import (
    BackupBundle,
    BackupFileEntry,
    BackupManifest,
    BackupScope,
    ExportFilter,
    ExportManifest,
    ExportTaskRef,
    RecoveryDrillRecord,
    RecoveryDrillStatus,
    RecoverySummary,
    RestoreConflict,
    RestoreConflictSeverity,
    RestoreConflictType,
    RestorePlan,
    SensitivityLevel,
)
from .checkpoint import (
    PIPELINE_NODES,
    CheckpointSnapshot,
    CheckpointStatus,
    ResumeAttempt,
    ResumeFailureType,
    ResumeResult,
    SideEffectLedgerEntry,
)
from .enums import (
    TERMINAL_STATES,
    VALID_TRANSITIONS,
    ActorType,
    EventType,
    PartType,
    RiskLevel,
    TaskStatus,
    validate_transition,
)
from .event import Event, EventCausality
from .execution import (
    ExecutionBackend,
    ExecutionConsoleSession,
    ExecutionEventKind,
    ExecutionRuntimeRecord,
    ExecutionSessionState,
    ExecutionStreamEvent,
    HumanInputPolicy,
    JobSpec,
)
from .message import MessageAttachment, NormalizedMessage
from .operator_inbox import (
    OperatorActionKind,
    OperatorActionOutcome,
    OperatorActionRequest,
    OperatorActionResult,
    OperatorActionSource,
    OperatorInboxItem,
    OperatorInboxResponse,
    OperatorInboxSummary,
    OperatorItemKind,
    OperatorItemState,
    OperatorQuickAction,
    PairingActionTarget,
    RetryLaunchRef,
)
from .orchestrator import (
    DispatchEnvelope,
    OrchestratorRequest,
    WorkerExecutionStatus,
    WorkerResult,
    WorkerRuntimeState,
    WorkerSession,
)
from .payloads import (
    ArtifactCreatedPayload,
    BackupLifecyclePayload,
    ChatImportLifecyclePayload,
    CheckpointSavedPayload,
    ErrorPayload,
    ExecutionCancelRequestedPayload,
    ExecutionInputAttachedPayload,
    ExecutionInputRequestedPayload,
    ExecutionLogPayload,
    ExecutionStatusChangedPayload,
    ExecutionStepPayload,
    ModelCallCompletedPayload,
    ModelCallFailedPayload,
    ModelCallStartedPayload,
    OperatorActionAuditPayload,
    OrchestratorDecisionPayload,
    ResumeFailedPayload,
    ResumeStartedPayload,
    ResumeSucceededPayload,
    StateTransitionPayload,
    TaskCreatedPayload,
    TaskDriftDetectedPayload,
    TaskHeartbeatPayload,
    TaskMilestonePayload,
    ToolCallCompletedPayload,
    ToolCallFailedPayload,
    ToolCallStartedPayload,
    UserMessagePayload,
    WorkerDispatchedPayload,
    WorkerReturnedPayload,
)
from .project import (
    Project,
    ProjectBinding,
    ProjectBindingType,
    ProjectMigrationRollbackPlan,
    ProjectMigrationRun,
    ProjectMigrationStatus,
    ProjectMigrationSummary,
    ProjectMigrationValidation,
    ProjectStatus,
    Workspace,
    WorkspaceKind,
)
from .task import RequesterInfo, Task, TaskPointers
from .update import (
    InstallAttempt,
    InstallStatus,
    ManagedRuntimeDescriptor,
    MigrationStepKind,
    MigrationStepResult,
    RestartStrategy,
    RuntimeManagementMode,
    RuntimeStateSnapshot,
    UpdateAttempt,
    UpdateAttemptSummary,
    UpdateOverallStatus,
    UpdatePhaseName,
    UpdatePhaseResult,
    UpdatePhaseStatus,
    UpdateTriggerSource,
    UpgradeFailureReport,
    VerifyStatus,
    utc_now,
)

__all__ = [
    # 枚举
    "TaskStatus",
    "EventType",
    "ActorType",
    "RiskLevel",
    "PartType",
    "ExecutionBackend",
    "ExecutionSessionState",
    "ExecutionEventKind",
    "HumanInputPolicy",
    # 状态机
    "VALID_TRANSITIONS",
    "TERMINAL_STATES",
    "validate_transition",
    # Task
    "Task",
    "RequesterInfo",
    "TaskPointers",
    # Event
    "Event",
    "EventCausality",
    # Artifact
    "Artifact",
    "ArtifactPart",
    # Backup / Restore / Export
    "BackupScope",
    "SensitivityLevel",
    "RestoreConflictType",
    "RestoreConflictSeverity",
    "RecoveryDrillStatus",
    "BackupFileEntry",
    "BackupManifest",
    "BackupBundle",
    "RestoreConflict",
    "RestorePlan",
    "ExportFilter",
    "ExportTaskRef",
    "ExportManifest",
    "RecoveryDrillRecord",
    "RecoverySummary",
    # Update / Runtime
    "InstallStatus",
    "UpdateTriggerSource",
    "UpdateOverallStatus",
    "UpdatePhaseName",
    "UpdatePhaseStatus",
    "RuntimeManagementMode",
    "RestartStrategy",
    "MigrationStepKind",
    "VerifyStatus",
    "InstallAttempt",
    "ManagedRuntimeDescriptor",
    "RuntimeStateSnapshot",
    "MigrationStepResult",
    "UpdatePhaseResult",
    "UpgradeFailureReport",
    "UpdateAttempt",
    "UpdateAttemptSummary",
    "utc_now",
    # Execution
    "JobSpec",
    "ExecutionRuntimeRecord",
    "ExecutionConsoleSession",
    "ExecutionStreamEvent",
    # Operator Inbox
    "OperatorItemKind",
    "OperatorItemState",
    "OperatorActionKind",
    "OperatorActionSource",
    "OperatorActionOutcome",
    "OperatorQuickAction",
    "RetryLaunchRef",
    "PairingActionTarget",
    "OperatorActionRequest",
    "OperatorActionResult",
    "OperatorInboxItem",
    "OperatorInboxSummary",
    "OperatorInboxResponse",
    # Checkpoint
    "PIPELINE_NODES",
    "CheckpointStatus",
    "ResumeFailureType",
    "CheckpointSnapshot",
    "ResumeAttempt",
    "ResumeResult",
    "SideEffectLedgerEntry",
    # Message
    "NormalizedMessage",
    "MessageAttachment",
    # Payloads
    "TaskCreatedPayload",
    "UserMessagePayload",
    "ModelCallStartedPayload",
    "ModelCallCompletedPayload",
    "ModelCallFailedPayload",
    "StateTransitionPayload",
    "ArtifactCreatedPayload",
    "BackupLifecyclePayload",
    "ChatImportLifecyclePayload",
    "ErrorPayload",
    "ExecutionStatusChangedPayload",
    "ExecutionLogPayload",
    "ExecutionStepPayload",
    "ExecutionInputRequestedPayload",
    "ExecutionInputAttachedPayload",
    "ExecutionCancelRequestedPayload",
    "OperatorActionAuditPayload",
    # Feature 008: Orchestrator Payloads
    "OrchestratorDecisionPayload",
    "WorkerDispatchedPayload",
    "WorkerReturnedPayload",
    # Feature 004: 工具调用 Payloads
    "ToolCallStartedPayload",
    "ToolCallCompletedPayload",
    "ToolCallFailedPayload",
    # Feature 010: Checkpoint / Resume Payloads
    "CheckpointSavedPayload",
    "ResumeStartedPayload",
    "ResumeSucceededPayload",
    "ResumeFailedPayload",
    "TaskHeartbeatPayload",
    "TaskMilestonePayload",
    "TaskDriftDetectedPayload",
    # Feature 008: Orchestrator Models
    "OrchestratorRequest",
    "DispatchEnvelope",
    "WorkerResult",
    "WorkerExecutionStatus",
    "WorkerRuntimeState",
    "WorkerSession",
    # Project / Workspace
    "ProjectStatus",
    "WorkspaceKind",
    "ProjectBindingType",
    "ProjectMigrationStatus",
    "Project",
    "Workspace",
    "ProjectBinding",
    "ProjectMigrationSummary",
    "ProjectMigrationValidation",
    "ProjectMigrationRollbackPlan",
    "ProjectMigrationRun",
]
