"""Control Plane 模型子包——按领域拆��，统一 re-export。

原 control_plane.py（1172 �� 90 个类）拆分为 8 个子模块。
所有消费方仍可通过 `from octoagent.core.models import XxxDocument` 导入。
"""

from ._base import (
    ControlPlaneActionStatus,
    ControlPlaneActor,
    ControlPlaneCapability,
    ControlPlaneDegradedState,
    ControlPlaneDocument,
    ControlPlaneEvent,
    ControlPlaneEventType,
    ControlPlaneResourceRef,
    ControlPlaneState,
    ControlPlaneSupportStatus,
    ControlPlaneSurface,
    ControlPlaneTargetRef,
)
from .agent import (
    AgentProfileItem,
    AgentProfilesDocument,
    CapabilityPackDocument,
    PolicyProfileItem,
    PolicyProfilesDocument,
    SkillGovernanceDocument,
    SkillGovernanceItem,
    WorkerProfileDynamicContext,
    WorkerProfileRevisionItem,
    WorkerProfileRevisionsDocument,
    WorkerProfilesDocument,
    WorkerProfileStaticConfig,
    WorkerProfileViewItem,
)
from .automation import (
    ActionDefinition,
    ActionRegistryDocument,
    ActionRequestEnvelope,
    ActionResultEnvelope,
    AutomationJob,
    AutomationJobDocument,
    AutomationJobItem,
    AutomationJobRun,
    AutomationJobStatus,
    AutomationScheduleKind,
)
from .memory import (
    MemoryConsoleDocument,
    MemoryConsoleFilter,
    MemoryConsoleSummary,
    MemoryProposalAuditDocument,
    MemoryProposalAuditItem,
    MemoryProposalSummary,
    MemoryRecordProjection,
    MemorySubjectHistoryDocument,
    VaultAccessGrantItem,
    VaultAccessRequestItem,
    VaultAuthorizationDocument,
    VaultRetrievalAuditItem,
)
from .retrieval import (
    CorpusKind,
    EmbeddingProfile,
    IndexBuildJob,
    IndexBuildJobStage,
    IndexGeneration,
    IndexGenerationStatus,
    MemoryRetrievalBindingItem,
    MemoryRetrievalProfile,
    RetrievalCorpusState,
    RetrievalPlatformDocument,
)
from .session import (
    A2AConversationItem,
    A2AMessageItem,
    AgentRuntimeItem,
    AgentSessionContinuityItem,
    ContextContinuityDocument,
    ContextFrameItem,
    ContextSessionItem,
    MemoryNamespaceItem,
    OwnerProfileDocument,
    RecallFrameItem,
    SessionProjectionDocument,
    SessionProjectionItem,
    SessionProjectionSummary,
)
from .setup import (
    BlockingReason,
    ConfigFieldHint,
    ConfigSchemaDocument,
    DiagnosticsFailureSummary,
    DiagnosticsSubsystemStatus,
    DiagnosticsSummaryDocument,
    McpProviderCatalogDocument,
    McpProviderItem,
    ProjectOption,
    ProjectSelectorDocument,
    SetupGovernanceDocument,
    SetupGovernanceSection,
    SetupReviewSummary,
    SetupRiskItem,
    WizardSessionDocument,
    WizardStepDocument,
)
from .work import (
    DelegationPlaneDocument,
    PipelineRunItem,
    SkillPipelineDocument,
    WorkProjectionItem,
)

__all__ = [
    # _base
    "ControlPlaneActionStatus",
    "ControlPlaneActor",
    "ControlPlaneCapability",
    "ControlPlaneDegradedState",
    "ControlPlaneDocument",
    "ControlPlaneEvent",
    "ControlPlaneEventType",
    "ControlPlaneResourceRef",
    "ControlPlaneState",
    "ControlPlaneSupportStatus",
    "ControlPlaneSurface",
    "ControlPlaneTargetRef",
    # session
    "A2AConversationItem",
    "A2AMessageItem",
    "AgentRuntimeItem",
    "AgentSessionContinuityItem",
    "ContextContinuityDocument",
    "ContextFrameItem",
    "ContextSessionItem",
    "MemoryNamespaceItem",
    "OwnerProfileDocument",
    "RecallFrameItem",
    "SessionProjectionDocument",
    "SessionProjectionItem",
    "SessionProjectionSummary",
    # agent
    "AgentProfileItem",
    "AgentProfilesDocument",
    "CapabilityPackDocument",
    "PolicyProfileItem",
    "PolicyProfilesDocument",
    "SkillGovernanceDocument",
    "SkillGovernanceItem",
    "WorkerProfileDynamicContext",
    "WorkerProfileRevisionItem",
    "WorkerProfileRevisionsDocument",
    "WorkerProfilesDocument",
    "WorkerProfileStaticConfig",
    "WorkerProfileViewItem",
    # memory
    "MemoryConsoleDocument",
    "MemoryConsoleFilter",
    "MemoryConsoleSummary",
    "MemoryProposalAuditDocument",
    "MemoryProposalAuditItem",
    "MemoryProposalSummary",
    "MemoryRecordProjection",
    "MemorySubjectHistoryDocument",
    "VaultAccessGrantItem",
    "VaultAccessRequestItem",
    "VaultAuthorizationDocument",
    "VaultRetrievalAuditItem",
    # retrieval
    "CorpusKind",
    "EmbeddingProfile",
    "IndexBuildJob",
    "IndexBuildJobStage",
    "IndexGeneration",
    "IndexGenerationStatus",
    "MemoryRetrievalBindingItem",
    "MemoryRetrievalProfile",
    "RetrievalCorpusState",
    "RetrievalPlatformDocument",
    # setup
    "ConfigFieldHint",
    "ConfigSchemaDocument",
    "DiagnosticsFailureSummary",
    "DiagnosticsSubsystemStatus",
    "DiagnosticsSummaryDocument",
    "McpProviderCatalogDocument",
    "McpProviderItem",
    "ProjectOption",
    "ProjectSelectorDocument",
    "BlockingReason",
    "SetupGovernanceDocument",
    "SetupGovernanceSection",
    "SetupReviewSummary",
    "SetupRiskItem",
    "WizardSessionDocument",
    "WizardStepDocument",
    # work
    "DelegationPlaneDocument",
    "PipelineRunItem",
    "SkillPipelineDocument",
    "WorkProjectionItem",
    # automation
    "ActionDefinition",
    "ActionRegistryDocument",
    "ActionRequestEnvelope",
    "ActionResultEnvelope",
    "AutomationJob",
    "AutomationJobDocument",
    "AutomationJobItem",
    "AutomationJobRun",
    "AutomationJobStatus",
    "AutomationScheduleKind",
]
