import { describe, expect, it } from "vitest";
import type { ControlPlaneSnapshot } from "../../types";
import {
  CONTROL_RESOURCE_QUERY_REGISTRY,
  resolveResourceRoutes,
} from "../contracts";
import {
  listWorkbenchResourceRoutes,
  mergeSnapshotResources,
} from "./controlPlaneResources";

function buildSnapshot(): ControlPlaneSnapshot {
  return {
    contract_version: "1.0.0",
    generated_at: "2026-03-13T00:00:00Z",
    registry: {
      contract_version: "1.0.0",
      resource_type: "action_registry",
      resource_id: "actions:registry",
      schema_version: 1,
      generated_at: "2026-03-13T00:00:00Z",
      updated_at: "2026-03-13T00:00:00Z",
      status: "ready",
      degraded: { is_degraded: false, reasons: [], unavailable_sections: [] },
      warnings: [],
      capabilities: [],
      refs: {},
      actions: [],
    },
    resources: {
      config: {
        contract_version: "1.0.0",
        resource_type: "config_schema",
        resource_id: "config:octoagent",
        schema_version: 1,
        generated_at: "2026-03-13T00:00:00Z",
        updated_at: "2026-03-13T00:00:00Z",
        status: "ready",
        degraded: { is_degraded: false, reasons: [], unavailable_sections: [] },
        warnings: [],
        capabilities: [],
        refs: {},
        schema: {},
        ui_hints: {},
        current_value: {},
        validation_rules: [],
        bridge_refs: [],
        secret_refs_only: true,
      },
      project_selector: {
        contract_version: "1.0.0",
        resource_type: "project_selector",
        resource_id: "project:selector",
        schema_version: 1,
        generated_at: "2026-03-13T00:00:00Z",
        updated_at: "2026-03-13T00:00:00Z",
        status: "ready",
        degraded: { is_degraded: false, reasons: [], unavailable_sections: [] },
        warnings: [],
        capabilities: [],
        refs: {},
        current_project_id: "project-default",
        current_workspace_id: "workspace-default",
        default_project_id: "project-default",
        fallback_reason: "",
        switch_allowed: true,
        available_projects: [],
        available_workspaces: [],
      },
      sessions: {
        contract_version: "1.0.0",
        resource_type: "session_projection",
        resource_id: "sessions:overview",
        schema_version: 1,
        generated_at: "2026-03-13T00:00:00Z",
        updated_at: "2026-03-13T00:00:00Z",
        status: "ready",
        degraded: { is_degraded: false, reasons: [], unavailable_sections: [] },
        warnings: [],
        capabilities: [],
        refs: {},
        focused_session_id: "",
        focused_thread_id: "",
        new_conversation_token: "",
        sessions: [],
        operator_summary: {
          total_pending: 0,
          approvals: 0,
          alerts: 0,
          retryable_failures: 0,
          pairing_requests: 0,
          degraded_sources: [],
          generated_at: "2026-03-13T00:00:00Z",
        },
        operator_items: [],
      },
      worker_profiles: {
        contract_version: "1.0.0",
        resource_type: "worker_profiles",
        resource_id: "worker-profiles:overview",
        schema_version: 1,
        generated_at: "2026-03-13T00:00:00Z",
        updated_at: "2026-03-13T00:00:00Z",
        status: "ready",
        degraded: { is_degraded: false, reasons: [], unavailable_sections: [] },
        warnings: [],
        capabilities: [],
        refs: {},
        active_project_id: "project-default",
        active_workspace_id: "workspace-default",
        profiles: [],
        summary: {},
      },
      context_continuity: {
        contract_version: "1.0.0",
        resource_type: "context_continuity",
        resource_id: "context:frames",
        schema_version: 1,
        generated_at: "2026-03-13T00:00:00Z",
        updated_at: "2026-03-13T00:00:00Z",
        status: "ready",
        degraded: { is_degraded: false, reasons: [], unavailable_sections: [] },
        warnings: [],
        capabilities: [],
        refs: {},
        frames: [],
        summary: {},
      },
      capability_pack: {
        contract_version: "1.0.0",
        resource_type: "capability_pack",
        resource_id: "capability:bundled",
        schema_version: 1,
        generated_at: "2026-03-13T00:00:00Z",
        updated_at: "2026-03-13T00:00:00Z",
        status: "ready",
        degraded: { is_degraded: false, reasons: [], unavailable_sections: [] },
        warnings: [],
        capabilities: [],
        refs: {},
        pack: {
          pack_id: "pack:1",
          version: "1.0.0",
          skills: [],
          tools: [],
          worker_profiles: [],
          bootstrap_files: [],
          fallback_toolset: [],
          degraded_reason: "",
          generated_at: "2026-03-13T00:00:00Z",
        },
        selected_project_id: "project-default",
        selected_workspace_id: "workspace-default",
      },
      skill_governance: {
        contract_version: "1.0.0",
        resource_type: "skill_governance",
        resource_id: "skill:governance",
        schema_version: 1,
        generated_at: "2026-03-13T00:00:00Z",
        updated_at: "2026-03-13T00:00:00Z",
        status: "ready",
        degraded: { is_degraded: false, reasons: [], unavailable_sections: [] },
        warnings: [],
        capabilities: [],
        refs: {},
        governance_version: 1,
        providers: [],
        installed_skills: [],
        recommendations: [],
        summary: {},
      },
      mcp_provider_catalog: {
        contract_version: "1.0.0",
        resource_type: "mcp_provider_catalog",
        resource_id: "mcp-providers:catalog",
        schema_version: 1,
        generated_at: "2026-03-13T00:00:00Z",
        updated_at: "2026-03-13T00:00:00Z",
        status: "ready",
        degraded: { is_degraded: false, reasons: [], unavailable_sections: [] },
        warnings: [],
        capabilities: [],
        refs: {},
        providers: [],
        summary: {},
      },
      setup_governance: {
        contract_version: "1.0.0",
        resource_type: "setup_governance",
        resource_id: "setup:governance",
        schema_version: 1,
        generated_at: "2026-03-13T00:00:00Z",
        updated_at: "2026-03-13T00:00:00Z",
        status: "ready",
        degraded: { is_degraded: false, reasons: [], unavailable_sections: [] },
        warnings: [],
        capabilities: [],
        refs: {},
        review: {
          ready: true,
          blocking_reasons: [],
          next_actions: [],
          summary: "",
        },
      },
      delegation: {
        contract_version: "1.0.0",
        resource_type: "delegation_plane",
        resource_id: "delegation:overview",
        schema_version: 1,
        generated_at: "2026-03-13T00:00:00Z",
        updated_at: "2026-03-13T00:00:00Z",
        status: "ready",
        degraded: { is_degraded: false, reasons: [], unavailable_sections: [] },
        warnings: [],
        capabilities: [],
        refs: {},
        works: [],
        summary: {},
      },
      diagnostics: {
        contract_version: "1.0.0",
        resource_type: "diagnostics_summary",
        resource_id: "diagnostics:summary",
        schema_version: 1,
        generated_at: "2026-03-13T00:00:00Z",
        updated_at: "2026-03-13T00:00:00Z",
        status: "ready",
        degraded: { is_degraded: false, reasons: [], unavailable_sections: [] },
        warnings: [],
        capabilities: [],
        refs: {},
        overall_status: "ready",
        checks: [],
        channel_summary: {},
        runtime_flags: {},
      },
      memory: {
        contract_version: "1.0.0",
        resource_type: "memory_console",
        resource_id: "memory:console",
        schema_version: 1,
        generated_at: "2026-03-13T00:00:00Z",
        updated_at: "2026-03-13T00:00:00Z",
        status: "ready",
        degraded: { is_degraded: false, reasons: [], unavailable_sections: [] },
        warnings: [],
        capabilities: [],
        refs: {},
        active_project_id: "project-default",
        active_workspace_id: "workspace-default",
        filters: {
          scope_id: "",
          partition: "",
          layer: "",
          query: "",
          include_history: false,
          include_vault_refs: false,
          limit: 50,
        },
        records: [],
        summary: {
          sor_current_count: 0,
          fragment_count: 0,
          vault_ref_count: 0,
          proposal_count: 0,
        },
      },
    },
  } as unknown as ControlPlaneSnapshot;
}

describe("controlPlaneResources", () => {
  it("暴露稳定的 query registry routes", () => {
    expect(listWorkbenchResourceRoutes()).toEqual(
      expect.arrayContaining(Object.keys(CONTROL_RESOURCE_QUERY_REGISTRY))
    );
  });

  it("根据 resource refs 去重并映射 routes", () => {
    const routes = resolveResourceRoutes([
      {
        resource_type: "session_projection",
        resource_id: "sessions:overview",
        schema_version: 1,
      },
      {
        resource_type: "delegation_plane",
        resource_id: "delegation:overview",
        schema_version: 1,
      },
      {
        resource_type: "session_projection",
        resource_id: "sessions:overview",
        schema_version: 1,
      },
    ]);

    expect(routes).toEqual(["sessions", "delegation"]);
  });

  it("把刷新后的 payload 合并回 snapshot", () => {
    const snapshot = buildSnapshot();
    const merged = mergeSnapshotResources(snapshot, ["diagnostics"], [
      {
        ...snapshot.resources.diagnostics,
        overall_status: "degraded",
      },
    ]);

    expect(merged.resources.diagnostics.overall_status).toBe("degraded");
    expect(merged.resources.sessions.resource_id).toBe(
      snapshot.resources.sessions.resource_id
    );
    expect(merged.generated_at).not.toBe(snapshot.generated_at);
  });
});
